BEGIN TRANSACTION ISOLATION LEVEL  REPEATABLE READ;

UPDATE Employees
SET Salary = 57000
WHERE Employee = 'Jack';
SELECT * FROM Employees;

SAVEPOINT JackUpdated;

DELETE FROM Employees
WHERE  Salary > 50000;

SELECT * FROM Employees;

ROLLBACK TRANSACTION TO SAVEPOINT JackUpdated;

SELECT * FROM Employees;

ROLLBACK TRANSACTION;

SELECT * FROM Employees;