-- working with TDL
DROP TABLE IF EXISTS T CASCADE;
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;

CREATE TABLE T(Col1 INT PRIMARY KEY);

SELECT * FROM T;

ROLLBACK TRANSACTION;

SELECT * FROM T;
-- Error 